# Header
menu:
  Home: /
  Archives: /archives
rss: /atom.xml
sitemap: /sitemap.xml
ga: /ga.html

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- recent_posts
- category
- tagcloud
- archive


# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: true

# Miscellaneous
google_analytics: UA-89925013-1
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:
